[core] fix(NumericInput): disabled prop prevents button interactions
palantir/blueprint pull request #4214
Opened 2020-07-07 22:47 UTC by ejose19

#### Fixes #4213

Also fixes a bug where disabled element allowed interacting with the buttonHandlers (due to now using AnchorButton)

#### Checklist

- [X] Includes tests
- [X] Update documentation

#### Changes proposed in this pull request:

- Add missing class to sass to handle control-group fill
- Don't execute handleButtonClick if component is disabled

#### Reviewers should focus on:

#### Screenshot

2020-07-10 02:39 UTC, adidahiya requested changes
thanks for the contribution. in the future I would appreciate separate PRs for unrelated issues/features.

2020-07-10 02:39 UTC, adidahiya commented on packages/core/src/components/forms/numericInput.tsx
> +                    if (this.props.disabled) return;
I am surprised we don't have a lint rule for this... I swear we used to... please use `{ }` braces for all if statements.

2020-07-10 02:39 UTC, adidahiya commented on packages/core/src/components/forms/numericInput.tsx
> +                    if (this.props.disabled) return;
also I think this check should go outside the `if (Keys.isKeyboardClick)` statement... or just be merged into the same conditional

2020-07-10 02:39 UTC, adidahiya commented on packages/core/test/controls/numericInputTests.tsx
> +        it("must set fill class on controlGroup element when fill is enabled", () => {
we don't need this test, it's tautological and doesn't add much value

2020-07-10 02:39 UTC, adidahiya commented on packages/core/src/components/forms/_control-group.scss
> +  &.#{$ns}-fill {
while looking into this bug I found some strange code which I don't think should exist. we have special logic in the control group example to make the "fill" option work on the page... this logic is outside the Blueprint API so it's misleading for developers testing the component. please remove these lines in this PR: https://github.com/palantir/blueprint/blob/842b2bb43f43ad11b71cdec86fff410d1a14474c/packages/docs-app/src/examples/core-examples/controlGroupExample.tsx#L46-L49

2020-07-10 02:50 UTC, ejose19 commented
@adidahiya Sure, adjusted files. Will take your notes in consideration for next PRs

2020-07-10 02:57 UTC, adidahiya approved these changes

2020-07-10 02:59 UTC, merged

2020-07-24 16:27 UTC, ejose19 commented
@adidahiya Is there any estimate where all the NumericInput changes will be released on npm?

2020-07-24 17:13 UTC, adidahiya commented
@ejose19 this was released. you can see which releases a commit is included in here:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/723999/88417183-7f7b9d80-cdaf-11ea-8a06-57fc1d16c3ea.png">

2020-07-24 17:26 UTC, ejose19 commented
@adidahiya If it's not much trouble, can you tell me where do I see exactly that? I checked all "tabs" on current page but I can't find that.

2020-07-24 18:50 UTC, ejose19 commented
@adidahiya Thanks, didn't know about that feature.