feat: data-connection
palantir/blueprint pull request #4336
Opened 2020-09-18 18:49 UTC by jheadrick2

#### Fixes #0000

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

#### Reviewers should focus on:

#### Screenshot

2020-09-18 18:49 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @jheadrick2! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2020-09-21 16:24 UTC, adidahiya commented on resources/icons/16px/bp3-data-connection-16.svg
> +<?xml version="1.0" encoding="UTF-8"?>
the name of this file does not match the icon name. it must be `data-connection.svg`, as shown in the [build failure](https://app.circleci.com/pipelines/github/palantir/blueprint/376/workflows/7bcbd439-021d-4f93-b20e-aae13fd5ae47/jobs/35040):

```
lerna ERR! yarn run compile stderr:
(node:248) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/circleci/project/resources/icons/16px/data-connection.svg'
```

2020-09-21 16:25 UTC, adidahiya commented on packages/icons/resources/icons/icons.json
> +      }
```suggestion
    }
```

2020-09-21 19:04 UTC, adidahiya commented
[docs preview](https://35070-71939872-gh.circle-artifacts.com/0/packages/docs-app/dist/index.html#icons)

the icon doesn't show up correctly, it renders a blank box:
 
<img width="350" alt="image" src="https://user-images.githubusercontent.com/723999/93809861-cead4580-fc1b-11ea-9371-7f7c37ed4e6b.png">

2020-09-21 19:07 UTC, adidahiya requested changes

2020-09-21 19:07 UTC, adidahiya commented on resources/icons/16px/data-connection.svg
> +    <defs>
please re-export these icons with simpler SVG definitions similar to the other icons in the repo. see my comment here https://github.com/palantir/blueprint/pull/4132#discussion_r427577589

2020-09-21 22:16 UTC, adidahiya commented on resources/icons/20px/data-connection.svg
> +    </g>
```suggestion
    <g id="bp3-data-connection" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <path d="M2,11.9 C2.93468865,12.5742236 4.3389668,13.1169578 6.02286947,13.4360955 C6.00757687,13.6215864 6,13.8099083 6,14 C6,16.5467063 7.359945,18.77577 9.39321594,20.00055 C5.40462513,19.9811517 2.16168117,18.9170543 2.00586153,17.5992952 L2,17.5 L2,11.9 Z M13,8 C16.315,8 19,10.685 19,14 C19,17.315 16.315,20 13,20 C9.685,20 7,17.315 7,14 C7,10.685 9.685,8 13,8 Z M14,9 L10,15 L12.5,15 L12,19 L16,13 L13.5,13 L14,9 Z M16.9995124,4.4 L16.9999712,8.2549186 C15.8661123,7.46390447 14.487116,7 12.9997725,7 C9.73921075,7 6.99933978,9.22941453 6.22127541,12.2470809 C3.81335585,11.8555478 2.12414114,11.0452198 2.00655427,10.1049899 L2,10 L2,4.4 C3.52495043,5.5 6.29986022,6.25 9.4997562,6.25 C12.6996522,6.25 15.474562,5.5 16.9995124,4.4 Z M9.4997562,0 C13.6371217,0 16.9995124,1.125 16.9995124,2.5 C16.9995124,3.875 13.6371217,5 9.4997562,5 C5.3498911,5 2,3.875 2,2.5 C2,1.125 5.3498911,0 9.4997562,0 Z" id="path-1"></path>
    </g>
```

2020-09-21 22:25 UTC, adidahiya commented
[docs preview](https://35233-71939872-gh.circle-artifacts.com/0/packages/docs-app/dist/index.html#icons) looks good

2020-09-21 22:25 UTC, adidahiya approved these changes

2020-09-21 22:25 UTC, merged