#3578 formatLabel boolean if it is on the thumb.
palantir/blueprint pull request #4471
Opened 2021-01-05 03:38 UTC by naughton

#### Fixes #3578

#### Checklist

- [x] Includes tests
- [ ] Update documentation
can update docs if it looks like this PR will be accepted.

#### Changes proposed in this pull request:

add a boolean (always true) to formatLabel callback, that indicates the value should be formatted for the thumb, not the axis.

#### Reviewers should focus on:

#### Screenshot

![image](https://user-images.githubusercontent.com/80646/103603794-4b5ee980-4ec4-11eb-9f0c-076d59aa6056.png)

Here on this Date range selector, we would like to add the DAY of the month to the thumb, but not to the axis.

2021-01-05 03:38 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @naughton! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2021-01-07 17:24 UTC, adidahiya requested changes
thanks for the PR. left some minor comments

2021-01-07 17:24 UTC, adidahiya commented on packages/core/src/components/slider/multiSlider.tsx
> +    labelRenderer?: boolean | ((value: number, isHandle?: boolean) => string | JSX.Element);
for a bit of forwards compatibility if we add more options here:

```suggestion
    labelRenderer?: boolean | ((value: number, opts?: { isHandleTooltip: boolean; }) => string | JSX.Element);
```

2021-01-07 17:24 UTC, adidahiya commented on packages/core/src/components/slider/multiSlider.tsx
>       *
we need some more docs here about the new feature...

```suggestion
     *
     * The callback is provided a numeric value and optional rendering options, which include:
     * - isHandleTooltip: whether this label is being rendered within a handle tooltip
     *
```

2021-01-07 18:14 UTC, adidahiya approved these changes

2021-01-07 18:16 UTC, merged