EditableText: Call updateInputDimensions only when the props it depends on change
palantir/blueprint pull request #4723
Opened 2021-05-17 16:08 UTC by SatishGandham

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:
`componentDidUpdate` of Editable text calls `updateInputDimensions` on every rerender, this triggers the layout calculations.
This PR addresses that issue by only calling `updateInputDimensions`  only when the props it depends on change

ref: https://github.com/palantir/blueprint/pull/4639#issuecomment-820503242

#### Reviewers should focus on:

Confirm if calling `updateInputDimensions` conditionally is a safe change

2021-05-18 16:15 UTC, adidahiya commented
@SatishGandham thanks for taking my suggestion and running with it. Looks like it is an incomplete implementation and will need to be adjusted / tweaked to get the right behavior. There are a few problems with this approach right now.

(1) The input is not expanding its height past its minLines to accommodate longer text:

<img width="814" alt="image" src="https://user-images.githubusercontent.com/723999/118686292-e2707200-b7d1-11eb-9673-ea0a933cae06.png">

(2) When switching to `alwaysRenderInput={false}`, the component collapses completely:

![2021-05-18 12 14 38](https://user-images.githubusercontent.com/723999/118687111-a689dc80-b7d2-11eb-965c-3c7729a0a0d4.gif)

2021-05-18 16:15 UTC, adidahiya requested changes
see my feedback above

2021-05-18 17:21 UTC, SatishGandham commented
@adidahiya 
Is `alwaysRenderInput` expected to change during components lifetime?

2021-05-18 17:32 UTC, SatishGandham commented
@adidahiya, Made the necessary changes.
We are now watching `state.value` and `props.alwaysRenderInput`

2021-05-19 17:59 UTC, adidahiya approved these changes

2021-05-19 18:00 UTC, merged

2021-05-19 18:00 UTC, adidahiya commented
thanks @SatishGandham!

2021-05-19 20:40 UTC, iamakulov commented
Thank you @SatishGandham 🙌 Never got time to finish the implementation in #4639 myself.