Add prop to ignore max and min date ranges
palantir/blueprint pull request #4786
Opened 2021-06-29 19:20 UTC by robertcoopercode

#### Fixes #877

#### Checklist

- [x] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

Allows selecting dates that fall outside of the `minDate` and `maxDate`.

`minDate` and `maxDate` are still useful to narrow the dropdown options for the available years in the date picker, but if a user wants to select a year outside the min/max (e.g. using the date input), it should still be allowed.

#### Reviewers should focus on:

#### Screenshot

2021-06-29 19:20 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @robertcoopercode! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2022-04-29 15:25 UTC, adidahiya requested changes
sorry for the very delayed review @robertcoopercode, are you still interested in pursuing this PR?

I will merge develop into your branch so we can get a docs preview build working again

2022-04-29 15:25 UTC, adidahiya commented on packages/datetime/src/datePickerCore.tsx
> +    ignoreRange?: boolean;
I don't think this is the best name, especially in the context of DateRangePicker and DateRangeInput. A better name would be `ignoreBounds`.

2022-04-29 15:25 UTC, adidahiya commented on packages/datetime/src/dateRangePicker.tsx
> +            return;
this seems wrong, there is no need to skip prop validation here in this case. can you describe the problem you were trying to avoid?

2022-04-29 15:35 UTC, adidahiya commented
Actually I can't push to your branch (you probably have that setting turned off for maintainers to push to forks), so I created a branch in this repo: https://github.com/palantir/blueprint/pull/5277

2022-04-29 17:32 UTC, adidahiya commented
There are some bugs, see my comment https://github.com/palantir/blueprint/pull/5277#issuecomment-1113556622

2023-05-12 16:39 UTC, adidahiya commented
Closing as stale, leave a comment if you want to pick this back up

2023-05-12 16:39 UTC, closed without merging