Fix PanelStack2 animation direction in controlled mode
palantir/blueprint pull request #4800
Opened 2021-07-05 13:05 UTC by invliD

#### Fixes #4686

I have a cherry-pick onto v4's renamed PanelStack ready locally (based on #4799, so not pushing just yet).

2021-07-09 21:05 UTC, adidahiya requested changes
the gist of the change seems reasonable, but it causes issues when `renderActivePanelOnly={false}`, the page crashes:

![2021-07-09 17 04 12](https://user-images.githubusercontent.com/723999/125135927-d28d5400-e0d7-11eb-8a7b-53b5d964d5da.gif)

2021-07-09 21:05 UTC, adidahiya commented on packages/core/src/components/panel-stack2/panelStack2.tsx
> +import React, { useEffect, useMemo, useRef } from "react";
please revert this line, we need to continue using the namespace import, because otherwise it's a breaking change to force consumers to use esModuleInterop + allowSyntheticDefaultImports

2021-07-12 11:33 UTC, invliD commented
@adidahiya That crash is actually not caused by this PR. I've found two issues that would cause a crash due to inconsistent number of hooks called:
1. Hooks are called after this early return:
    https://github.com/palantir/blueprint/blob/55f89fa7aa79a0bfe95120a8295cfb5b7d1b12a8/packages/core/src/components/panel-stack2/panelStack2.tsx#L95-L99

1. The `renderPanel` function is _called_, not added as a JSX.Element. This is the issue the example is running into when using controlled mode (in fact just the 2-line change switching the example to controlled mode reproduces the issue). If a component uses hooks, it _must_ be created as a JSX.Element, otherwise the hook calls are attributed to the parent component. In that case, unless the current panel or all panels _together_ (depending on renderActivePanelOnly) call the same number of hooks, we'll run into that crash.
    https://github.com/palantir/blueprint/blob/55f89fa7aa79a0bfe95120a8295cfb5b7d1b12a8/packages/core/src/components/panel-stack2/panelView2.tsx#L89-L93
    I believe the three options we have are either (1) pretend renderPanel is a component and call createElement for it, (2) wrap each renderPanel call in a simple FC that essentially takes ownership of potential hook calls, or (3) break typings of renderPanel to disallow passing of an FC itself, always requiring a function. Not sure that one's possible.

Either way, given that the issue already exists, let's fix that in a follow-up.

2021-07-12 20:33 UTC, adidahiya approved these changes

2021-07-12 20:37 UTC, adidahiya commented
Filed https://github.com/palantir/blueprint/issues/4807 for follow-up bug

2021-07-12 20:38 UTC, merged