Capture focus when it returns to the document
palantir/blueprint pull request #4907
Opened 2021-09-14 21:22 UTC by michael-yx-wu

#### Fixes #0000

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

#### Reviewers should focus on:

#### Screenshot

Before -- focus would not return to overlay if coming back to the document from somewhere outside (e.g. url, native browser controls)

![2021-09-14 17 19 46](https://user-images.githubusercontent.com/3681045/133335522-d34c0188-683d-4f9d-8b83-a55eb6524bda.gif)

After -- focus immediately returns to overlay

![2021-09-14 17 21 39](https://user-images.githubusercontent.com/3681045/133335723-5f453766-6e86-4f13-b375-80f9e7bf923a.gif)

2021-09-14 21:26 UTC, michael-yx-wu commented on packages/core/src/components/overlay/overlay.tsx
> -                    tabIndex: this.props.enforceFocus || this.props.autoFocus ? 0 : undefined,
removing this fixes an issue w/ the omnibar where the container _and_ the input are both focusable, even though you probably don't want the container to be focusable in that situation. now that we have focus traps, this doesn't seem necessary. if consumers want non-focusable elements to be focusable, they will need to take care to set tabindex themselves. not sure if this constitutes a break

2021-09-15 15:54 UTC, adidahiya requested changes
code is a little convoluted, but seems ok...

there is a bug now with dialog focus... seems a little too aggressive. you can't focus the primary button or the close button via the TAB key:

![2021-09-15 11 54 01](https://user-images.githubusercontent.com/723999/133467269-e774f673-55ba-4aed-8e58-935caed287dd.gif)

2021-09-16 19:29 UTC, michael-yx-wu commented
I think this is a result of the infinite focus bug due to `shouldReturnFocusOnClose` that was fixed in 49a2a4622f85518280a50d71d7a3809cd6f7ed34. Merged in develop and it works properly now:
![Uploading 2021-09-16 15.23.52.gif…]()

2021-09-20 20:58 UTC, adidahiya approved these changes

2021-09-20 20:58 UTC, merged