[core] docs(Button): buttons are disabled when loading={true}
palantir/blueprint pull request #4978
Opened 2021-10-21 17:28 UTC by danny-does-stuff

#### Checklist

- [ ] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

Clarify that the `loading` prop on `IButtonProps` will also disable the button

#### Reviewers should focus on:

The docs

2021-10-21 17:28 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @dannyharding10! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2021-10-22 14:52 UTC, adidahiya requested changes

2021-10-22 14:52 UTC, adidahiya commented on packages/core/src/components/button/abstractButton.tsx
> +     * If set to `true`, the button will display a centered loading spinner instead of its contents, and the button will be disabled.
we don't actually set the `disabled` attribute, so I think this change is more appropriate:

```suggestion
     * If set to `true`, the button will display a centered loading spinner instead of its contents, and the button will appear disabled.
```

2021-10-22 15:25 UTC, danny-does-stuff commented on packages/core/src/components/button/abstractButton.tsx
> +     * If set to `true`, the button will display a centered loading spinner instead of its contents, and the button will be disabled.
@adidahiya According to [this line](https://github.com/palantir/blueprint/blob/758233c54de4bb707a76131507938a11d7d72e1b/packages/core/src/components/button/abstractButton.tsx#L121), the button does actually get disabled when `loading` is set. Am I reading it wrong?

2021-10-22 15:37 UTC, adidahiya approved these changes

2021-10-22 15:38 UTC, adidahiya commented on packages/core/src/components/button/abstractButton.tsx
> +     * If set to `true`, the button will display a centered loading spinner instead of its contents, and the button will be disabled.
hmm wait, you are right. sorry about that, will revert my edit!

2021-10-22 15:38 UTC, adidahiya commented on packages/core/src/components/button/abstractButton.tsx
> +     * If set to `true`, the button will display a centered loading spinner instead of its contents, and the button will appear disabled.
```suggestion
     * If set to `true`, the button will display a centered loading spinner instead of its contents, and the button will be disabled.
```

2021-10-22 15:38 UTC, danny-does-stuff commented on packages/core/src/components/button/abstractButton.tsx
> +     * If set to `true`, the button will display a centered loading spinner instead of its contents, and the button will be disabled.
Awesome thanks!

2021-10-22 15:39 UTC, merged