[v4] [core] Update Input borders and separate buttons
palantir/blueprint pull request #5055
Opened 2021-12-01 21:35 UTC by johnly13

#### Fixes #0000

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:
* Update default borders
* Detach buttons for control groups with buttons (e.g. `NumericInput`)
* Inset border focus states

#### Reviewers should focus on:

#### Screenshot

2021-12-01 21:35 UTC, johnly13 commented on packages/core/src/blueprint.scss
> -// Input variables and overrides
Moved all of these overrides + styles to `components/forms/*`

2021-12-01 21:36 UTC, johnly13 commented on packages/core/src/common/_variables.scss
> +$pt-input-box-shadow: inset 0px 1px 1px rgba(17, 20, 24, 0.5),
Updated default borders for light theme
![Screen Shot 2021-12-01 at 16 36 10](https://user-images.githubusercontent.com/5934779/144317887-730c78ff-3c13-4dc8-8641-beae525d77b0.png)

2021-12-01 21:37 UTC, johnly13 commented on packages/core/src/common/_variables.scss
> +$pt-dark-input-box-shadow: inset 0 1px 0 0 rgba(17, 20, 24, 0.6),
Updated default borders for dark theme
![Screen Shot 2021-12-01 at 16 36 40](https://user-images.githubusercontent.com/5934779/144317950-977d8e0a-9ed9-4af0-96c6-3ff9722315b0.png)

2021-12-01 21:38 UTC, johnly13 commented on packages/core/src/components/forms/_common.scss
> +      inset border-shadow(1, $color, 1px),
add inset focus border for light theme and reduce outer border to 2px
![Screen Shot 2021-12-01 at 16 37 54](https://user-images.githubusercontent.com/5934779/144318097-bb7267ed-8351-4aa3-8b72-3379a6e14112.png)

2021-12-01 21:38 UTC, johnly13 commented on packages/core/src/components/forms/_common.scss
> +      inset border-shadow(1, $color, 1px),
add inset focus border for dark theme and reduce outer border to 2px
![Screen Shot 2021-12-01 at 16 38 17](https://user-images.githubusercontent.com/5934779/144318154-1a290215-f683-45ab-bd10-7f0a9ab9d99b.png)

2021-12-01 21:39 UTC, johnly13 commented on packages/core/src/components/forms/_control-group.scss
> -
removed all logic for removing borders between consecutive components

2021-12-01 21:39 UTC, johnly13 commented on packages/core/src/components/forms/_control-group.scss
> -  // Add border radius inheritance to support components wrapped in a popover
removed all logic to unround border-radius for consecutive components

2021-12-01 21:40 UTC, johnly13 commented on packages/core/src/components/forms/_control-group.scss
> +      margin-right: 2px;
detach buttons from input
![Screen Shot 2021-12-01 at 16 39 46](https://user-images.githubusercontent.com/5934779/144318346-523ed872-0c32-443d-b89e-e11dfaf8166d.png)

with focus:
![Screen Shot 2021-12-01 at 16 39 58](https://user-images.githubusercontent.com/5934779/144318377-b332f617-b6f0-4403-a2f3-65554747aa1b.png)

2021-12-01 21:41 UTC, johnly13 commented on packages/core/src/components/forms/_input-group.scss
> +          @include pt-dark-input-intent(map-get($pt-dark-input-intent-box-shadow-colors, $intent));
use of `$color4` for dark mode intent input within input group moved to here
![Screen Shot 2021-12-01 at 16 41 41](https://user-images.githubusercontent.com/5934779/144318594-67a60457-8097-459a-9feb-85fdcb770c50.png)

2021-12-01 21:42 UTC, johnly13 commented on packages/core/src/components/forms/_input.scss
> +        @include pt-dark-input-intent(map-get($pt-dark-input-intent-box-shadow-colors, $intent));
same as above but for non-input group dark inputs

2021-12-01 21:43 UTC, johnly13 commented on packages/core/src/components/forms/_numeric-input.scss
> -    &:first-child {
removed all logic to unround border-radius for consecutive components in numeric input

2021-12-02 15:58 UTC, adidahiya requested changes
the focus style changes generally look ok... for example here's a danger intent numeric input:
![2021-12-02 10 57 35](https://user-images.githubusercontent.com/723999/144457254-082513c8-f82c-461a-a3ec-95adc621d936.gif)

but there seems to be a problem with tag input styles, this doesn't seem right:
![2021-12-02 10 57 45](https://user-images.githubusercontent.com/723999/144457308-7a766752-afd5-46a7-adaa-cac0c67cd4f8.gif)

2021-12-02 15:58 UTC, adidahiya commented on packages/core/src/common/_variables.scss
> +$pt-input-box-shadow: inset 0px 1px 1px rgba(17, 20, 24, 0.5),
I think these should all use `$black` instead of `17, 20, 24`...

```suggestion
$pt-input-box-shadow: inset 0px 1px 1px rgba($black, 0.5),
```

2021-12-02 21:22 UTC, johnly13 commented on packages/core/src/components/tag-input/_tag-input.scss
> -    @each $intent, $color in $pt-intent-text-colors {
fixes the colors for tag input active borders
![Screen Shot 2021-12-02 at 16 20 41](https://user-images.githubusercontent.com/5934779/144505065-0bbf928a-7675-4d02-b2b0-31354a2bd56a.png)

2021-12-02 21:24 UTC, johnly13 commented
added a tag input example to the demo app and updated the colors for tag input active borders

2021-12-02 22:14 UTC, adidahiya approved these changes

2021-12-02 22:15 UTC, merged