feat: new icons - ship, ship-cargo
palantir/blueprint pull request #5075
Opened 2021-12-16 23:39 UTC by jennyfan

#### Fixes #0000

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

Adds icons `ship` and `ship-cargo`

#### Reviewers should focus on:

Make sure everything renders okay at appropriate sizes, and that the right files were changed.

#### Screenshot

<img width="723" alt="Screen Shot 2021-12-16 at 6 39 09 PM" src="https://user-images.githubusercontent.com/2983898/146464833-1960806a-7445-44a6-bc6d-e555dfe3029b.png">
if any. -->

2021-12-16 23:39 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @jennyfan! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2022-01-05 17:10 UTC, adidahiya requested changes

2022-01-05 17:10 UTC, adidahiya commented on packages/icons/resources/icons/icons.json
> +        "tags": "transportation, cargo, cargo ship, freight, ship, boat, cruise, yacht, move, supply, supply chain, shipping container, shipping",
don't need "cargo ship" when both individual words exist in the tags list already

```suggestion
        "tags": "transportation, cargo, freight, ship, boat, cruise, yacht, supply, supply chain, container, shipping",
```

2022-01-05 17:10 UTC, adidahiya commented on packages/icons/resources/icons/icons.json
> +        "tags": "transportation, ship, boat, cruise, yacht, move, supply, supply chain, trip, shipping",
```suggestion
        "tags": "transportation, ship, boat, cruise, yacht, supply, supply chain, trip, shipping",
```

2022-01-05 17:10 UTC, adidahiya commented on packages/icons/resources/icons/icons.json
> +        "iconName": "ship-cargo",
let's just call this "cargo-ship" and make the API more intuitive... will need to rename the SVG files too

```suggestion
        "iconName": "cargo-ship",
```

2022-01-05 17:11 UTC, adidahiya commented
new icons look good in the [PR preview](https://50328-71939872-gh.circle-artifacts.com/0/packages/docs-app/dist/index.html#icons), though! 👍🏽

2022-01-06 20:20 UTC, jennyfan reviewed
Submitting reviewer changes

2022-01-06 20:24 UTC, jennyfan reviewed
Renaming files to cargo-ship

2022-01-07 00:10 UTC, adidahiya approved these changes

2022-01-07 00:10 UTC, merged