Allow background color for dialog to be overridden
palantir/blueprint pull request #5086
Opened 2022-01-04 18:59 UTC by dylangrandmont

#### Checklist

- [x] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

Allow override of dialog `background-color` using a variable `$pt-dialog-background-color`

#### Reviewers should focus on:

* Naming convention of variable
* Appropriateness of using a variable here
* Whether this needs to be documented (it appears that component-level variables like this are not documented elsewhere)

2022-01-04 18:59 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @dylangrandmont! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2023-10-03 15:45 UTC, adidahiya requested changes
sorry for the very delayed review here! please let me know if you'd like to continue working on this PR.

I'm open to this code change but have some comments on the implementation.

Note that we'll also need a corresponding dark theme color variable called `$dark-dialog-background-color`.

2023-10-03 15:45 UTC, adidahiya commented on packages/core/src/components/dialog/_dialog.scss
> +$pt-dialog-background-color: $light-gray4 !default;
this should match the naming convention of the other dialog variables:

```suggestion
$dialog-background-color: $light-gray4 !default;
```

2024-01-08 14:20 UTC, adidahiya approved these changes

2024-01-08 14:36 UTC, merged

2024-01-08 15:51 UTC, dylangrandmont commented
Thanks for taking this over the line @adidahiya