[icons] fix: pre-es2017 compatibility
palantir/blueprint pull request #5098
Opened 2022-01-16 00:10 UTC by gluxon

#### Fixes #0000

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

#### Reviewers should focus on:

#### Screenshot

2022-01-16 00:10 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @gluxon! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2022-01-16 00:35 UTC, gluxon commented
Did a quick smoke test to make sure this didn't affect the contents of `IconNames`.

```sh
❯ cd packages/icons

# Before
❯ git reset --hard ORIG_HEAD
HEAD is now at 4dac1637 Publish
❯ node -e 'console.log(Object.keys(require("./lib/cjs/iconNames").IconNames).length)'
1078
❯ node -e 'console.log(require("./lib/cjs/iconNames"))' | md5sum
8cb0237c9ed0ff2db4679aed00f76a00  -

# After
❯ git reset --hard ORIG_HEAD
HEAD is now at 1bcd43e7 [v4] [icons] fix: pre-es2017 compatibility
❯ yarn compile  
❯ node -e 'console.log(Object.keys(require("./lib/cjs/iconNames").IconNames).length)'
1078
❯ node -e 'console.log(require("./lib/cjs/iconNames"))' | md5sum
8cb0237c9ed0ff2db4679aed00f76a00  -
```

2022-01-18 17:51 UTC, adidahiya requested changes
Since we already require a few [modern language features](https://blueprintjs.com/docs/versions/4/#blueprint/getting-started.language-features) to use Blueprint (including a few which are not fully supported in IE11 and thus require polyfills), I'd rather take a different approach.

Rather than add backwards-compatible code for IE11, let's instead update the docs to indicate that `Object.values()` support is now required at runtime with Blueprint v4.0. Users can [polyfill it with core-js](https://github.com/zloirock/core-js#objectvalues--objectentries).

We are planning to completely remove support for IE11 anyway soon (I'll add a deprecation notice to the docs before the v4.0 stable release).

2022-01-18 18:58 UTC, gluxon commented
Sounds good to me. Thanks for taking a look @adidahiya. 🙂

2022-01-18 18:58 UTC, closed without merging