Popover2 popupkind
palantir/blueprint pull request #5300
Opened 2022-05-13 19:36 UTC by dlech

#### Fixes #0000

#### Checklist

- [x] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:
This adds a new `popupKind` property to the `Popover2` component for controlling the `aria-haspopup` attribute of the target element.

The current implementation hard-codes `aria-haspopup` to "true" which means that the popup is a menu. However, this is not true in all cases. Furthermore, the `aria-haspopup` attribute should not be set for tooltips since they are not interactive elements. So if the interaction kind is a hover interaction, this new property is ignored.

Reference: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-haspopup

#### Reviewers should focus on:

#### Screenshot

Before:
![image](https://user-images.githubusercontent.com/963645/168376271-3c165826-1d50-4683-b6dc-a03027abd5bf.png)

After:
![image](https://user-images.githubusercontent.com/963645/168377299-67a73279-b205-463a-82b5-91588af39a1b.png)

2022-05-26 15:21 UTC, adidahiya requested changes

2022-05-26 15:21 UTC, adidahiya commented on packages/popover2/src/popover2.tsx
> +export enum Popover2PopupKind {
I think we can generalize this enum name and just call it `PopupKind`, and move it to a new file `popupKind.ts` in this package. Also please include a link to the [docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-haspopup) in the JSDoc for this symbol.

2022-05-26 15:21 UTC, adidahiya commented on packages/popover2/src/popover2.tsx
> +     * @default true for click interactions, false for hover interactions
thanks for fixing the typos :)

2022-05-26 15:21 UTC, adidahiya commented on packages/popover2/src/popover2.tsx
> +            "aria-haspopup": this.props.popupKind ?? (isHoverInteractionKind ? undefined : "true"),
I think this should be only `undefined` if `this.props.interactionKind === Popover2InteractionKind.HOVER_TARGET_ONLY`.

in the case of `Popover2InteractionKind.HOVER` popovers, you _can_ still interact with the content, and we have instances of that in our applications. so haspopup should be set to something.

when you make this change, please make sure to update the new prop JSDoc.

2022-05-26 15:21 UTC, adidahiya commented on packages/popover2/test/popover2Tests.tsx
> +            wrapper = renderPopover({ isOpen: true, interactionKind: Popover2InteractionKind.HOVER });
this test will have to be updated if you make my change suggested above.

2022-06-02 22:33 UTC, dlech commented on packages/popover2/src/popover2.tsx
> +export enum Popover2PopupKind {
done

2022-06-02 22:33 UTC, dlech commented on packages/popover2/src/popover2.tsx
> +            "aria-haspopup": this.props.popupKind ?? (isHoverInteractionKind ? undefined : "true"),
done

2022-06-02 22:33 UTC, dlech commented on packages/popover2/test/popover2Tests.tsx
> +            wrapper = renderPopover({ isOpen: true, interactionKind: Popover2InteractionKind.HOVER });
done

2022-06-03 14:23 UTC, adidahiya approved these changes

2022-06-03 14:23 UTC, adidahiya commented
thanks @dlech!

2022-06-03 14:24 UTC, merged