feat: new icon - float
palantir/blueprint pull request #5309
Opened 2022-05-18 10:23 UTC by float-icon

#### Fixes #0000

#### Checklist

- [ ] Update documentation

#### Changes proposed in this pull request:

Adds a float icon reading "1.0".

#### Screenshot

![20px_float](https://user-images.githubusercontent.com/105726246/169017622-e6aa9540-b7b9-47af-a02c-854db952d7d7.svg)
![16px_float](https://user-images.githubusercontent.com/105726246/169017628-9fcdd745-1b1d-4433-9559-74a225ea2a46.svg)

2022-05-18 10:23 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @float-icon! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2022-05-18 18:33 UTC, adidahiya requested changes
SVGs look good, but I'd like to change the metadata

2022-05-18 18:33 UTC, adidahiya commented on packages/icons/icons.json
> +        "group": "interface",
let's put it into Miscellaneous with the other (array) data types. the icons list is due for a re-organization some time; we should have a separate category for data types...

```suggestion
        "group": "miscellaneous",
```

2022-05-18 18:33 UTC, adidahiya commented on packages/icons/icons.json
> +        "iconName": "float",
I think we should be more specific and call this "floating-point". You will need to rename the SVG files to match the iconName here after you do that.

```suggestion
        "displayName": "Floating point number",
        "iconName": "floating-point",
```

2022-05-19 09:35 UTC, float-icon commented
> SVGs look good, but I'd like to change the metadata

done

2022-05-19 12:18 UTC, adidahiya approved these changes

2022-05-19 12:18 UTC, merged