Add timezone aware components
palantir/blueprint pull request #5322
Opened 2022-05-25 09:37 UTC by vhellem

Adds a new package with time zone aware date input component, that is not dependent on `moment-timezone` for fetching a list of timezones, but instead depends on `date-fns`. 

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

#### Reviewers should focus on:

- API for date input component

#### Screenshot

2022-05-25 15:57 UTC, adidahiya commented
The new timezone picker has much worse performance than the old one:

| TimezonePicker | TimezonePickerV2 |
| - | - |
| ![2022-05-25 11 56 17](https://user-images.githubusercontent.com/723999/170305604-e4ffbbf7-25af-4a46-8470-94944b589fb1.gif) | ![2022-05-25 11 54 39](https://user-images.githubusercontent.com/723999/170305469-262cd5fe-8bd6-44d3-89e5-ca45b45c7ad6.gif) |

we'll need to dig into this with browser performance profiling...

2022-05-26 08:50 UTC, vhellem commented
> 

Done a number of improvements. Main drawback was probably that we rendered all items initially vs just a subset list, which I've added. Also done a lot more preprocessing.

2022-06-01 19:40 UTC, adidahiya requested changes, later dismissed
(1) The package name "datetime-timezone-aware" is fairly verbose, I’d like to avoid that. I think we can just go with "datetime2" and make things easier for consumers, with the assumption that many of our users do care about timezones and want their datetime UIs to be timezone-aware. The new dependencies [jstimezonedetect](https://bundlephobia.com/package/jstimezonedetect@1.0.7), [date-fns-tz](https://bundlephobia.com/package/date-fns-tz@1.3.4), and [date-fns](https://bundlephobia.com/package/date-fns@2.28.0) are not too large, especially with bundle modularity & tree-shaking applied.

Then we would also drop “timezone aware” from the component names... `TimezoneAwareDateInput` becomes simply `DateInput2`.

(2) Note that I’m getting this warning in the console:

```
Warning: Encountered two children with the same key, America/New_York. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

(3) It would be great if the TimezonePicker2 example could display the offset in the button like TimezonePicker does:

<img width="265" alt="image" src="https://user-images.githubusercontent.com/723999/171433770-80558826-346b-4906-9f1e-c44064e64fcb.png">

(4) I’m noticing the timezone-aware date input example has similar performance issues like I noted earlier with TimezonePicker2, we should fix this:

![2022-06-01 11 25 05](https://user-images.githubusercontent.com/723999/171447006-d9e1ac3a-e945-42e6-b310-0c1e38a96563.gif)

(5) API feedback... I think we should support controlled usage of `timezone` in addition to uncontrolled usage via `defaultTimezone`... a user may want to _always_ show the picker in a certain timezone. And we should allow both _hiding_ and _disabling_ of the timezone picker (`disableTimezonePicker` + `hideTimezonePicker`). Otherwise, this overall API seems ok, using ISO strings only instead of Date values. We will have to add some props validation after adding a `timezone` prop... for example if the controlled `timezone` prop value doesn’t match the timezone offset present in the `value` ISO string, we should log an error and choose one to take precedence over the other.

(6) I don’t love the fact that this component has two popovers. I generally try to discourage multi-overlay UIs wherever possible. But this approach is fine as a first draft. I can take a stab at improving the embedded timezone selector UI after this PR is merged.

(7) The timezone tag and calendar icon appear interactive, but they don’t trigger anything on click. Clicking the timezone tag should go directly to the timezone select. The calendar button feels superfluous, it could just be a `leftIcon` on the InputGroup, I think.

2022-06-01 19:40 UTC, adidahiya commented on packages/datetime/src/datePicker.tsx
> +                <div className={Classes.DATEPICKER_CONTENT}>
note to self: consider a different name for this class, like "datepicker main panel" or something

2022-06-01 19:40 UTC, adidahiya commented on packages/datetime/src/datePickerCore.tsx
> +    footerComponent?: JSX.Element;
this isn't a component, it's an element:

```suggestion
    footerElement?: JSX.Element;
```

comment should be updated to match

2022-06-01 19:40 UTC, adidahiya commented on packages/docs-app/src/examples/datetime-examples/datePickerExample.tsx
> +                    <Callout>This additional footer component can be displayed below the date picker</Callout>
this implementation is a little convoluted. you can just store a constant outside this component which is the sample footer element

```tsx
const exampleFooterElement = <Callout>This additional footer element can be displayed below the date picker</Callout>
```

store a boolean toggle flag instead of `footerComponent` in state

and then set the DatePicker prop:

```tsx
<DatePicker
    // ...
    footerElement={this.showFooterElement ? exampleFooterElement : undefined}
/>
```

2022-06-01 19:40 UTC, adidahiya commented on packages/docs-app/src/examples/datetime-examples/datePickerExample.tsx
> +                    label="Show a footer component"
```suggestion
                    label="Show custom footer element"
```

2022-06-01 19:40 UTC, adidahiya commented on packages/docs-app/src/examples/datetime-examples/datePickerExample.tsx
> +                />
remove duplicated code

```suggestion
```

2022-06-01 19:40 UTC, adidahiya commented on packages/datetime-timezone-aware/src/components/timezone-picker/timezone-picker-v2.md
> +`TimezonePickerV2` allows the user to select from a list of timezones. The list of times is coded into the library itself, and it does not depend on any external packages for updating the this list o
```suggestion
`TimezonePickerV2` allows the user to select from a list of timezones. The list is coded into the library itself, so it does not depend on any external packages for the list of timezones.
```

2022-06-01 19:40 UTC, adidahiya commented on packages/datetime-timezone-aware/src/components/timezone-picker/timezone-picker-v2.md
> +In supported browsers, the [i18n API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/resolvedOptions) is used.
we don't need to reference outdated browsers. the only one that doesn't support this part of the i18n API is IE11, and we are dropping support for that in Blueprint v5. Since this is a new package, we can mention that IE11 is not supported with this package. so this documentation can then just say:

```suggestion
We use the [browser `Intl` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/resolvedOptions).
```

2022-06-01 19:40 UTC, adidahiya commented on packages/datetime-timezone-aware/src/components/timezone-picker/timezone-picker-v2.md
> +In other browsers, `Date` methods and a population heuristic are used.
```suggestion
```

2022-06-02 05:53 UTC, vhellem commented on packages/datetime/src/datePicker.tsx
> +                <div className={Classes.DATEPICKER_CONTENT}>
Happy to update it myself as well?

2022-06-02 06:01 UTC, vhellem commented on packages/datetime-timezone-aware/src/components/timezone-picker/timezone-picker-v2.md
> +In other browsers, `Date` methods and a population heuristic are used.
Done, also removed `jstz` as what was what was being used to guess

2022-06-02 07:26 UTC, vhellem commented
Thanks so much for the review! A couple follow up questions

> (1) The package name "datetime-timezone-aware" is fairly verbose, I’d like to avoid that. I think we can just go with "datetime2" and make things easier for consumers,

Can do, although it feel's slightly weird to me that `datetime2` would depent on `datetime`? Although I guess we may eventually want to replace more of those? 

> (4) I’m noticing the timezone-aware date input example has similar performance issues like I noted earlier with TimezonePicker2, we should fix this:

Hmm, I can't really repro this here, as things are quite fast on my end. I imagine it has something to do with the initial render. The below suggestion of moving it to the right element may solve it. 

> (5) API feedback... I think we should support controlled usage of `timezone` in addition to uncontrolled usage via `defaultTimezone`... a user may want to _always_ show the picker in a certain timezone. And we should allow both _hiding_ and _disabling_ of the timezone picker (`disableTimezonePicker` + `hideTimezonePicker`). Otherwise, this overall API seems ok, using ISO strings only instead of Date values. We will have to add some props validation after adding a `timezone` prop... for example if the controlled `timezone` prop value doesn’t match the timezone offset present in the `value` ISO string, we should log an error and choose one to take precedence over the other.

Are you speaking specifically about the `DateInput` or the `TimezonePicker` now? We support borth hiding and disabling of the timezone picker in the `DateInput` component, so currently there's a way to achieve all of these by hiding/disabling the timezone picker and then passing `defaultTimezone`. I'm not sure if it's worth passing in an additional `timezoneValue` in addition to this, as it doesn't feel like what we want to control here? Could add it though, it just feel's like a place where we might want to be more opinionated about how it's being used. 


> (7) The timezone tag and calendar icon appear interactive, but they don’t trigger anything on click. Clicking the timezone tag should go directly to the timezone select. The calendar button feels superfluous, it could just be a `leftIcon` on the InputGroup, I think.

Removed the calendar all together. I see now that the `dateInput` component doesn't trigger an opening on the right elements, only on input focus itself. What do you think about rendering the timezone-picker itself as the right element? I think that would solve the performance issues (I'm struggling a bit to repro that),Then we could potentially just remove it from within the time picker itself as well to avoid having two popovers. Some styling changes would probably be needed

2022-06-03 16:51 UTC, adidahiya commented
The new timezone picker target in DateInput2 looks good!

(1) I find myself selecting the timezone text accidentally too often. I think we should disable that with `user-select: none`

<img width="139" alt="image" src="https://user-images.githubusercontent.com/723999/171909708-84daf48f-82b6-44f4-a207-dbdaa5215c9e.png">

(2) "disabling" the timezone picker prevents it from popping up, but it still appears interactive. I think you need to set `disabled` on the Tag or apply some custom styling:

![2022-06-03 12 47 07](https://user-images.githubusercontent.com/723999/171909745-7c32760e-ecba-4497-bad4-1cc9fc341bd6.gif)

(3) Disabling the overall DateInput2 does not disable the timezone picker; this is a bug:

![2022-06-03 12 47 31](https://user-images.githubusercontent.com/723999/171909861-6a59d3cb-6c15-464c-82e7-ed1c44209a1e.gif)

(4) as for my earlier request about setting `timezone` in a controlled manner instead of only allowing `defaultTimezone`... if you think that's not needed for now, I'm more than happy to punt it for a future PR and keep this one smaller

2022-06-09 18:41 UTC, merged