allow for passing an aria-label to the menu that gets created in MultiSelect2/Select2/Suggest2
palantir/blueprint pull request #5435
Opened 2022-07-12 01:20 UTC by bvandercar-vt

#### Fixes #0000

#### Checklist

- [N/A] Includes tests
- [N/A] Update documentation

in order to pass aXe a11y testing, we need to apply an `aria-label` to the `Menu` that is created by MultiSelect2/Select2/Suggest2

2022-07-12 08:08 UTC, bvandercar-vt commented
I am also open to renaming this prop ‘listProps’ or ‘listboxProps’ instead of ‘menuProps’, whatever the devs prefer

2022-07-20 01:23 UTC, adidahiya requested changes
looks good! just some minor docs edit suggestions

2022-07-20 01:23 UTC, adidahiya commented on packages/select/src/components/multi-select/multiSelect2.tsx
> +     * that contains the selectable options.
```suggestion
     * Props to spread to the `Menu` listbox containing the selectable options.
```

2022-07-20 01:23 UTC, adidahiya commented on packages/select/src/components/select/select2.tsx
> +     * that contains the selectable options.
```suggestion
     * Props to spread to the `Menu` listbox containing the selectable options.
```

2022-07-20 01:23 UTC, adidahiya commented on packages/select/src/components/suggest/suggest2.tsx
> +     * that contains the selectable options.
```suggestion
     * Props to spread to the `Menu` listbox containing the selectable options.
```

2022-07-20 02:45 UTC, adidahiya approved these changes

2022-07-20 02:46 UTC, merged