add Prop: panelDisabled to DialogStep to disable Navigation on the Step
palantir/blueprint pull request #5468
Opened 2022-07-26 21:18 UTC by christian1koch

#### Fixes #0000

#### Checklist

- [ x] Includes tests
- [ x] Update documentation (happens automatically since the prop description was added)

#### Changes proposed in this pull request:

Prop: panelDisabled is added to DialogStep. 

This allow to disable navigation on a specific panel of a DialogStep, which by adding the props to all DialogSteps, can disable the navigation through the panels altogether. This would solve https://github.com/palantir/blueprint/issues/5041 and potentially allow the fixes for : https://github.com/palantir/blueprint/issues/4872 & https://github.com/palantir/blueprint/issues/4871, since the dialogSteps could be disabled when submitting the Dialog on the last step.

The decision for having a step by step disable instead of an complete props.disableNavigation on the MultiStepDialog, is that there could be cases to where only some steps would like to be disabled and others not, thus having more control over the Dialog overall, and having a full disabled navigation state could be easily implemented using this prop.

#### Reviewers should focus on:

- Code Quality for the implementation, mainly on the css implementation (any improvements are welcome).
- That Disabling a Panel looks exactly like when the Step has been visited.

#### Screenshot

Step 2 disabled:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/66799199/181113456-48c9779d-aa2c-46ef-ac17-df27698d5158.png">

2022-07-26 21:18 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @christian1koch! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2022-08-01 20:24 UTC, christian1koch commented
This PR is ready for review.

2022-08-01 23:58 UTC, adidahiya commented
Thanks for the update @christian1koch, I will review this week.

2022-08-22 19:11 UTC, adidahiya requested changes
I think we should also add a demo for this prop to the docs example, something like a "Disable second step" toggle. Then we could easily test what the dialog looks like when `disable={true}` for one of the steps

2022-08-22 19:11 UTC, adidahiya commented on packages/core/src/components/dialog/dialogStep.tsx
> +    panelDisabled?: boolean;
I think this could simply be called `disabled`

```suggestion
    disabled?: boolean;
```

2022-08-22 19:11 UTC, adidahiya commented on packages/core/src/components/dialog/dialogStep.tsx
> +     * Disable panel for side navigation
```suggestion

    /**
     * Setting this to `false` will disable navigation to this step's panel via the steps list in the sidebar.
```

2022-08-22 19:11 UTC, adidahiya commented on packages/core/src/components/dialog/_multistep-dialog.scss
> +  &.#{$ns}-dialog-step-viewed.#{$ns}-dialog-step-disabled {
I think some of this Sass implementation could be cleaned up a bit to reduce duplication... I will take a stab at it by pushing a commit to the PR

2022-08-22 19:57 UTC, adidahiya commented
I pushed some of my suggested improvements and added a toggle to the docs example so that we can interactively test this new feature. There's still a problem where you can navigate to the disabled step in the example. See my code comment about this. I chose not to disable navigation via `nextButtonProps` / `backButtonProps` because that would defeat the purpose of adding the new toggle to the docs example (we wouldn't be able to move past the first step to see the new styling).

We'll have to think some more about how this `disabled` prop interacts with the footer actions rendered by MultistepDialog... users may want the option to either:
1. skip disabled steps ("Next" should go to the next available non-disabled step), or
1. automatically disable the "Next" button if the next step is `disabled={true}`

2022-08-23 00:05 UTC, christian1koch commented
I agree with your previous comment. I would vote for the first option and my reasoning behind this, is that there could be cases where you would want to "skip a step" depending on something selected on the current step. I believe the first option gives this component more possibilities to be used in different cases, while the second one would make the this prop too restrictive.

The first option also allows the user to recreate the second option, by disabling the following steps with the same conditions that disable the next button on the current step.

Overall IMO, the first option would make this component more "powerful". Any thoughts about this, @adidahiya?

2022-08-31 16:01 UTC, adidahiya commented
@christian1koch sounds good, let's go with the first option, to skip disabled steps. Can you add that to this PR?

2022-09-14 17:42 UTC, adidahiya commented
friendly ping @christian1koch, are you interested in finishing up this PR?

2022-09-14 17:57 UTC, christian1koch commented
@adidahiya Yes, sorry I've been kinda busy, I will start working on it this weekend most likely.

2024-01-03 17:23 UTC, closed without merging

2024-01-03 17:23 UTC, adidahiya commented
closing PR as stale for now, but these issues are still open for PRs