[core] adding tooltip to MultistepDialog back, next, final button
palantir/blueprint pull request #5534
Opened 2022-09-10 05:53 UTC by ohcnivek

#### Fixes #5519 

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

- adding an extra prop, ```tooltipContent```, to ```abstractButton.tsx``` props, which by association enables the prop  to exist on ```DialogStepButtonProps``` 
- renders tooltip on dialog step button if ```tooltipContent``` prop exists (user should define when it exists / doesnt, checkout the example. ```packages/docs-app/src/examples/core-examples/multistepDialogExample.tsx```)
- also adjusted the example in docs to reflect changes

#### Reviewers should focus on:
- typescript quality / implementation logic — followed what @adidahiya suggested in  #5519 

#### Screenshot
https://user-images.githubusercontent.com/64056046/189471022-580de65c-4790-4e95-ae6e-0a862ee989e4.mov

2022-09-10 05:53 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @ohcnivek! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2022-09-12 16:10 UTC, adidahiya requested changes

2022-09-12 16:10 UTC, adidahiya commented on packages/core/src/components/dialog/multistepDialog.tsx
> +import { Tooltip2 } from "../../../../popover2/src/tooltip2";
ah, you can't reach across packages in the monorepo to import modules like this. you have to do it through the public package APIs.

furthermore, since @blueprintjs/core does not depend on @blueprintjs/popover2 (it's designed not to), we can't use `Tooltip2` in this component. you'll have to use `Tooltip` even though it's deprecated. this shouldn't be a problem, though, since `Tooltip` will work fine for this simple use case, and in Blueprint v5 it will get automatically/seamlessly upgraded to use the `Tooltip2` implementation.

2022-09-12 16:10 UTC, adidahiya commented on packages/core/src/components/dialog/multistepDialog.tsx
> +            if (backButtonProps?.tooltipContent) {
please avoid implicit type coercion here. instead use an explicit check:

```suggestion
            if (backButtonProps?.tooltipContent != null) {
```

2022-09-12 16:10 UTC, adidahiya commented on packages/core/src/components/dialog/multistepDialog.tsx
> +                        <Button
please reduce the code repetition here by storing the button as a variable outside this conditional block:

```ts
const backButton = (
    <Button
        key="back"
        onClick={this.getDialogStepChangeHandler(selectedIndex - 1)}
        text="Back"
        {...backButtonProps}
    />
);
```

2022-09-12 16:10 UTC, adidahiya commented on packages/core/src/components/dialog/multistepDialog.tsx
> +                        <Button intent="primary" key="final" text="Submit" {...this.props.finalButtonProps} />
same here, I'd rather have this button defined in a `finalButton` variable and used twice

2022-09-12 16:10 UTC, adidahiya commented on packages/core/src/components/dialog/multistepDialog.tsx
> +            if (this.props.finalButtonProps?.tooltipContent) {
same here, please avoid implicit type coercion, and use an explicit check instead:

```suggestion
            if (this.props.finalButtonProps?.tooltipContent != null) {
```

2022-09-12 16:10 UTC, adidahiya commented on packages/core/src/components/dialog/multistepDialog.tsx
> +            if (nextButtonProps?.tooltipContent) {
```suggestion
            if (nextButtonProps?.tooltipContent != null) {
```

2022-09-12 16:10 UTC, adidahiya commented on packages/core/src/components/dialog/multistepDialog.tsx
> +                        <Button
same here, I'd rather have this button defined in a `nextButton` variable and used twice

2022-09-12 16:10 UTC, adidahiya commented on packages/docs-app/src/examples/core-examples/multistepDialogExample.tsx
> +                        tooltipContent: this.state.value === undefined ? "Needs an input." : null,
no need to use `null` here:

```suggestion
                        tooltipContent: this.state.value === undefined ? "Needs an input" : undefined,
```

2022-09-13 02:19 UTC, ohcnivek commented on packages/core/src/components/dialog/multistepDialog.tsx
> +import { Tooltip2 } from "../../../../popover2/src/tooltip2";
interesting — out of curiosity, what's the reason behind not being able to import across monorepos like that (other than @blueprint/core not depending on @blueprint/popover2)?

2022-09-13 20:48 UTC, adidahiya commented on packages/core/src/components/dialog/multistepDialog.tsx
> +import { Tooltip2 } from "../../../../popover2/src/tooltip2";
One of the main ideas/principles in monorepos is to create clear API boundaries between packages / projects in the monorepo. Code from package A should only be able to use public APIs exported from package B. This ensures that the code will work when the projects are packaged for distribution and published to NPM.

2022-09-13 20:51 UTC, adidahiya commented on packages/core/src/components/dialog/multistepDialog.tsx
> +import { Tooltip } from "@blueprintjs/core";
You don't need to import from `@blueprintjs/core` -- this _is_ the source code for that package. Within this package, you can import other components in the `src/` directory, just like you see below on L24 with `Button`, etc.

This import should be `from "../tooltip/tooltip";`

2022-09-13 21:10 UTC, adidahiya commented
There's another issue here -- Tooltips don't play nicely with disabled Buttons. This edge case will be common with the `tooltipContent`, as users will likely be showing something in the tooltip when the button is disabled. See the Button docs for more info. It's better to use an AnchorButton.

![2022-09-13 17 08 51](https://user-images.githubusercontent.com/723999/190009837-b63814c7-8f48-445b-a590-5dbe59d953c8.gif)

I'll push a commit here to make these fixes.

2022-09-13 21:47 UTC, adidahiya approved these changes

2022-09-14 13:19 UTC, adidahiya commented
[docs preview build](https://output.circle-artifacts.com/output/job/5d2de8fc-66a5-484c-b3a0-5718a95875fc/artifacts/0/packages/docs-app/dist/index.html#core/components/dialog.multistep-dialog) looks good 👍🏽

2022-09-14 13:19 UTC, merged