iOS: Input disabled state contrast fix
palantir/blueprint pull request #5641
Opened 2022-10-04 11:05 UTC by mduczek

#### Checklist

No additional documentation/tests necessary

#### Changes proposed in this pull request:

Fix or iOS specific styling, based on:
https://stackoverflow.com/questions/262158/disabled-input-text-color-on-ios
and:
https://stackoverflow.com/questions/30102792/css-media-query-to-target-only-ios-devices

#### Reviewers should focus on:

#### Screenshot

##### Before

<img width="481" alt="Screenshot 2022-10-04 at 12 06 38" src="https://user-images.githubusercontent.com/2834839/193803204-e74f5036-afab-477f-b25e-286ca4490a25.png">

<img width="482" alt="Screenshot 2022-10-04 at 12 05 21" src="https://user-images.githubusercontent.com/2834839/193803318-f9dbcdc5-c19b-42ee-af15-e18c5e93a85f.png">

##### After

<img width="1208" alt="Screenshot 2022-10-04 at 12 07 42" src="https://user-images.githubusercontent.com/2834839/193803402-f3b60b0a-113e-4449-9999-de04034f7094.png">

<img width="471" alt="Screenshot 2022-10-04 at 12 02 13" src="https://user-images.githubusercontent.com/2834839/193803441-cb523353-eaf4-420c-984e-152fc24357cc.png">

2022-10-04 13:49 UTC, adidahiya commented
regular text inputs look fine but the text in TagInput tags is now unreadable in iOS:

| Before | After |
| - | - |
| <img width="545" alt="image" src="https://user-images.githubusercontent.com/723999/193836761-6455f511-3a73-4d0a-b7d9-6c0bbc813c55.png"> | <img width="545" alt="image" src="https://user-images.githubusercontent.com/723999/193836842-c76769f1-1f39-4d93-920f-19d22a36f449.png"> |

2022-10-04 13:54 UTC, adidahiya requested changes
:-1: for TagInput regression described in my comment above

2022-10-04 13:54 UTC, adidahiya commented on packages/core/src/components/forms/_common.scss
> +  @supports (-webkit-touch-callout: none) {
please add a code comment explaining that this is for iOS support

2022-10-04 21:08 UTC, mduczek commented
Thanks for finding the issue with TagInput!

Given iOS renders only disabled `<input/>` in non-standard way, I changed the selector to only target `<input />`:

<img width="1286" alt="Screenshot 2022-10-04 at 22 40 03" src="https://user-images.githubusercontent.com/2834839/193928608-a052150f-19bf-42d0-888f-f35f95d955c9.png">

while testing I also noticed we should have an override for dark-mode, so added it as well :)

<img width="1286" alt="Screenshot 2022-10-04 at 23 01 32" src="https://user-images.githubusercontent.com/2834839/193929334-2737a87f-c1e1-465d-aab0-4fda0f35ac60.png">

2022-10-05 03:46 UTC, adidahiya approved these changes
lgtm, thanks @mduczek 👍🏽

2022-10-05 03:47 UTC, merged