Add new "at" icon
palantir/blueprint pull request #5670
Opened 2022-10-14 21:00 UTC by wangyuy22

#### Fixes #0000

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

Adds new icon for @ symbol.

#### Reviewers should focus on:

#### Screenshot

![image](https://user-images.githubusercontent.com/46030108/195943044-e5f8d641-5227-4087-aed9-38dc8996fc6d.png)

2022-10-14 21:00 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @wangyuy22! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2022-10-17 15:31 UTC, adidahiya requested changes
mostly looks good, just some minor feedback on icon metadata

<img width="66" alt="image" src="https://user-images.githubusercontent.com/723999/196219637-dae29ddc-68b0-44d0-a435-257a43f5b690.png">

2022-10-17 15:31 UTC, adidahiya commented on packages/icons/icons.json
> +        "tags": "email, mention",
```suggestion
        "tags": "email, mention, tag, address, asperand, rate of",
```

2022-10-17 15:31 UTC, adidahiya commented on packages/icons/icons.json
> +        "group": "file",
```suggestion
        "group": "miscellaneous",
```

2022-10-17 15:32 UTC, adidahiya approved these changes

2022-10-17 15:56 UTC, merged