migrating to MouseEvent() constructor to avoid using deprecated method
palantir/blueprint pull request #5680
Opened 2022-10-19 08:43 UTC by Anuragkillswitch

#### Fixes #5173 

#### Checklist

- [x] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

Updated the deprecated MouseEvent.initMouseEvent() to the new MouseEvent() constructor and passed the same arguments and correct defaults according to the new documentation.

#### Reviewers should focus on:

Proper corresponding arguments for the functions as provided in the documentation.

#### Screenshot

2022-10-19 14:05 UTC, adidahiya commented
@Anuragkillswitch please make sure to fix lint (`yarn lint-fix` in a package) and formatting (`yarn format` at the repo root). Let me know when the build passes and I'll review this PR.

2022-10-19 17:51 UTC, Anuragkillswitch commented
@adidahiya I ran the yarn lint-fix in the packages but it didn't give me any errors locally, can you suggest what to do ?

2022-10-19 19:35 UTC, Anuragkillswitch commented
@adidahiya I have formatted and fixed the lint and the checks have passed, can you take a look? Thanks!

2022-10-20 19:45 UTC, adidahiya requested changes
couple minor code style things, otherwise lgtm

2022-10-20 19:45 UTC, adidahiya commented on packages/test-commons/src/utils.ts
> -    // https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail
why remove this comment?

2022-10-20 19:45 UTC, adidahiya commented on packages/test-commons/src/utils.ts
>      let detailArg = 0;
```suggestion
    // see https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail
    let detailArg = 0;
```

2022-10-20 19:45 UTC, adidahiya commented on packages/test-commons/src/utils.ts
>      // eslint-disable-next-line deprecation/deprecation
wrong location for this MDN link, also we should remove the HACKHACK and eslint comment flag

```suggestion

```

2022-10-20 19:46 UTC, adidahiya approved these changes

2022-10-20 20:06 UTC, merged