feat: new icon - power poles
palantir/blueprint pull request #5682
Opened 2022-10-19 20:38 UTC by RexTheInnkeeper

#### Fixes #0000

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

added low and high voltage power pole icons

#### Reviewers should focus on:

make sure everything renders ok and correct files were changed

#### Screenshot

![Poles 20px](https://user-images.githubusercontent.com/107489230/196798469-eca28cdb-e40d-4d6b-816b-a3e8a803e2b8.png)
![Poles](https://user-images.githubusercontent.com/107489230/196798471-ca63a99f-e4b2-4569-97dd-800db5bb371d.png)

2022-10-19 20:38 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @RexTheInnkeeper! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2022-10-20 19:28 UTC, adidahiya requested changes
these icons don't show up correctly in the [docs preview build](https://output.circle-artifacts.com/output/job/ad292ee8-d0f6-41bc-a746-270353974a59/artifacts/0/packages/docs-app/dist/index.html#icons):

<img width="277" alt="image" src="https://user-images.githubusercontent.com/723999/197040025-b60e1242-cb26-47c8-b2fe-a335db71f24e.png">

<img width="270" alt="image" src="https://user-images.githubusercontent.com/723999/197040089-c0ac69fd-8fa6-4761-8b74-b962d49dd1c2.png">

2022-10-20 19:28 UTC, adidahiya commented on packages/icons/icons.json
> +   {
```suggestion
    {
```

2022-10-20 21:40 UTC, adidahiya commented
@RexTheInnkeeper there are still some issues with the 20px high voltage icon:

<img width="257" alt="image" src="https://user-images.githubusercontent.com/723999/197064166-3c9fb95d-1f28-46a9-a481-14099bc8539c.png">

2022-10-20 21:41 UTC, adidahiya requested changes

2022-10-20 21:41 UTC, adidahiya commented on resources/icons/20px/high-voltage-pole.svg
> +<g clip-path="url(#clip0_2240_7)">
I think you need to remove this `<g>`

2022-10-20 21:41 UTC, adidahiya commented on resources/icons/20px/high-voltage-pole.svg
> +<defs>
also remove these unnecessary `<defs>`

2022-10-21 13:20 UTC, adidahiya approved these changes
looks good now:

<img width="351" alt="image" src="https://user-images.githubusercontent.com/723999/197205266-f6a4e27e-60dd-40c9-bed5-d22be476def6.png">

I'm not sure if we'll keep a distinct category for "Utilities" icons like this, but it's fine for now. I'll probably reorganize some icons into a category for "map markers" or something like that.

2022-10-21 13:21 UTC, merged