Gr/intel icon
palantir/blueprint pull request #5856
Opened 2023-01-19 15:40 UTC by gredman2018

#### Fixes #0000

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

Added a the new intelligence icon with 16px and 20px

#### Reviewers should focus on:

Everything renders correctly at both sizes!

#### Screenshot

![Screenshot 2023-01-19 at 10 39 38 AM](https://user-images.githubusercontent.com/43188682/213486172-55e62a7f-2cb5-4de7-9084-88042dabd417.png)

2023-01-19 15:40 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @gredman2018! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2023-01-20 16:44 UTC, adidahiya requested changes
@CPerinet to confirm design approval 👍🏽 / 👎🏽 ?

2023-01-20 16:44 UTC, adidahiya commented on packages/icons/icons.json
> +
extra newline here is not allowed:

```suggestion
```

2023-01-20 16:44 UTC, adidahiya commented on packages/icons/icons.json
> +        "group": "interface",
is this really an interface icon? let's throw it in misc for now

```suggestion
        "group": "miscellaneous",
```

2023-01-20 16:45 UTC, adidahiya requested changes

2023-01-20 16:45 UTC, adidahiya commented on packages/icons/icons.json
> +
oops, missed this one

```suggestion
```

2023-01-20 16:45 UTC, adidahiya approved these changes

2023-01-20 16:55 UTC, adidahiya commented
sorry about the failing deploy-preview job -- I'll fix that -- here's the docs preview link: https://output.circle-artifacts.com/output/job/7ebf1edd-d362-4194-9fda-f8170c8baec9/artifacts/0/packages/docs-app/dist/index.html#icons

<img width="250" alt="image" src="https://user-images.githubusercontent.com/723999/213757303-03f9c8c7-90ff-4d7a-a93f-0356ccd93118.png">

2023-01-20 22:13 UTC, gredman2018 commented
Hi! When/how can I fix circleci deploy-preview failing?

2023-01-23 14:48 UTC, adidahiya commented
deploy-preview is returning a failing exit code because it's building on a fork and doesn't have the necessary environment variables. That's not a problem with your PR, just an issue with the preview script right now. It should exit gracefully with a successful exit code -- I'm going to fix that in a separate PR. In the meantime, I'll merge this PR, it's good to go :shipit:

2023-01-23 14:48 UTC, merged