feat: new icon - axle
palantir/blueprint pull request #5962
Opened 2023-02-20 18:09 UTC by tanmaybansal0

#### Fixes #0000

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

Added axle icon

#### Reviewers should focus on:

Making sure everything renders okay and the right files were changed

#### Screenshot

![axle](https://user-images.githubusercontent.com/94586052/220175783-be0a10ed-9416-4f43-92ad-8353ed26f15c.svg)
![axle](https://user-images.githubusercontent.com/94586052/220175819-9dede06c-c5ed-4290-ad13-d789652f3d56.svg)

2023-02-20 18:14 UTC, adidahiya commented
<h3>feat: new icon - axle</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/f61e7537-c13a-43a0-b3e3-321a7b041184/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/f61e7537-c13a-43a0-b3e3-321a7b041184/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/f61e7537-c13a-43a0-b3e3-321a7b041184/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/f61e7537-c13a-43a0-b3e3-321a7b041184/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

2023-02-21 14:57 UTC, adidahiya requested changes
failing formatting checks because of bad indentation

2023-02-21 14:57 UTC, adidahiya commented on packages/icons/icons.json
> +    "codepoint": 62264
```suggestion
        "displayName": "Axle",
        "iconName": "axle",
        "tags": "axle, shaft, rail, train, wheels",
        "group": "interface",
        "codepoint": 62264
```

2023-02-21 14:58 UTC, adidahiya requested changes

2023-02-21 14:58 UTC, adidahiya commented on packages/icons/icons.json
> +    "group": "interface",
also I don't think this is an interface icon

```suggestion
    "group": "miscellaneous",
```

2023-02-21 17:02 UTC, tanmaybansal0 commented on packages/icons/icons.json
> +    "codepoint": 62264
Updated

2023-02-21 17:11 UTC, adidahiya commented
<h3>update formatting</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/03c67c55-f443-4284-ba9a-c670546d2a00/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/03c67c55-f443-4284-ba9a-c670546d2a00/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/03c67c55-f443-4284-ba9a-c670546d2a00/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/03c67c55-f443-4284-ba9a-c670546d2a00/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

2023-02-21 17:19 UTC, adidahiya approved these changes
looks fine in PR preview:

<img width="70" alt="image" src="https://user-images.githubusercontent.com/723999/220415162-eaf711b1-de18-4f9e-bdd2-1147139a0ddf.png">

2023-02-21 17:19 UTC, merged