add small prop to numeric and file inputs
palantir/blueprint pull request #6071
Opened 2023-04-15 03:52 UTC by tmisirpash

#### Fixes #5035 

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

#### Reviewers should focus on:

#### Screenshot

2023-04-15 03:52 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @tmisirpash! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2023-04-17 21:26 UTC, adidahiya requested changes
thanks @tmisirpash, can you please also add a demo for these new props to both `fileInputExample.tsx` and `numericInputBasicExample.tsx`?

2023-04-18 13:17 UTC, adidahiya requested changes
looks good in the [docs preview build](https://output.circle-artifacts.com/output/job/7bd24968-5878-4f65-8bcc-38fe9e2c2f15/artifacts/0/packages/docs-app/dist/index.html#core/components/file-input)! and thanks for adding CSS API support.

just left a few code style comments, otherwise this is good to go :shipit:

2023-04-18 13:17 UTC, adidahiya commented on packages/core/src/components/forms/_file-input.scss
> +$pt-input-height-small-difference: $pt-input-height-small - $pt-button-height-smaller;
nit: no need for this variable, just inline its value on the next line

```suggestion
```

2023-04-18 13:17 UTC, adidahiya commented on packages/core/src/components/forms/_file-input.scss
> +$file-input-button-padding-small: $pt-input-height-small-difference * 0.5 !default;
```suggestion
$file-input-button-padding-small: ($pt-input-height-small - $pt-button-height-smaller) * 0.5 !default;
```

2023-04-18 14:46 UTC, tmisirpash commented on packages/core/src/components/forms/_file-input.scss
> +$pt-input-height-small-difference: $pt-input-height-small - $pt-button-height-smaller;
@adidahiya Done, but I had to disable the max-line-length lint rule for it to work

2023-04-18 16:29 UTC, adidahiya approved these changes

2023-04-18 16:29 UTC, merged