added new icon(group, input)
palantir/blueprint pull request #6573
Opened 2023-11-28 19:54 UTC by ju-won

#### Fixes #0000

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

Added group and input icons

#### Reviewers should focus on:

Making sure everything renders okay and the right files were changed.

#### Screenshot

2023-11-28 19:54 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @ju-won! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2023-11-29 13:54 UTC, adidahiya requested changes

2023-11-29 13:54 UTC, adidahiya commented on packages/icons/icons.json
> +        "iconName": "group",
discussed over Slack, please rename this to be more specific, either:

1. "widget-group"
2. "widget-set"
3. "set-item"
4. "group-item"
5. "item-in-group"

2023-11-29 15:12 UTC, adidahiya approved these changes
lgtm in [docs preview](https://output.circle-artifacts.com/output/job/c2d7b92c-968d-4edf-8636-1f662e5f9062/artifacts/0/packages/docs-app/dist/index.html#icons/icons-list)

![image](https://github.com/palantir/blueprint/assets/723999/3a115c02-2eeb-4d21-a7dd-991978ea360b)

2023-11-29 15:14 UTC, merged