Add EntityTitle component
palantir/blueprint pull request #6590
Opened 2023-12-07 17:15 UTC by mud

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:
Add a new `EntityTitle` component which generalizes a popular UI pattern.

#### Reviewers should focus on:
This PR addresses the review left on #6278

#### Screenshot
![Screenshot 2023-12-07 at 9 15 26 AM](https://github.com/palantir/blueprint/assets/16532/66f62901-186a-403f-9403-8cc63bea3896)

2023-12-07 17:23 UTC, adidahiya commented
<h3>clean up</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/7ce6a445-b347-4701-8474-5103f72e2efb/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/7ce6a445-b347-4701-8474-5103f72e2efb/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/7ce6a445-b347-4701-8474-5103f72e2efb/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/7ce6a445-b347-4701-8474-5103f72e2efb/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

2023-12-08 01:53 UTC, adidahiya commented
<h3>remove heading size</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/a9b37ba6-2b9f-408b-8c19-13eca2db3756/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/a9b37ba6-2b9f-408b-8c19-13eca2db3756/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/a9b37ba6-2b9f-408b-8c19-13eca2db3756/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/a9b37ba6-2b9f-408b-8c19-13eca2db3756/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

2023-12-08 05:53 UTC, adidahiya commented
<h3>add tests</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/35b23a2f-af5f-43ea-a6fe-e50f4b6496f0/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/35b23a2f-af5f-43ea-a6fe-e50f4b6496f0/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/35b23a2f-af5f-43ea-a6fe-e50f4b6496f0/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/35b23a2f-af5f-43ea-a6fe-e50f4b6496f0/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

2023-12-08 15:32 UTC, adidahiya commented
<h3>update demo example</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/747a1274-908a-4237-96ee-a22940e044c7/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/747a1274-908a-4237-96ee-a22940e044c7/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/747a1274-908a-4237-96ee-a22940e044c7/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/747a1274-908a-4237-96ee-a22940e044c7/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

2024-01-05 22:07 UTC, adidahiya requested changes
looks great overall! thanks for pushing through this feature @mud 

my one bit of feedback about the interactive example is that it looks a bit too much like a checkbox, and visitors might feel prompted to click it as a to-do list item

<img width="377" alt="image" src="https://github.com/palantir/blueprint/assets/723999/98743946-5fe4-413c-be55-32c4fcd81d6b">

an alternative icon suggestion here might be "add-to-artifact":

<img width="397" alt="image" src="https://github.com/palantir/blueprint/assets/723999/4da2d1b4-ca8a-46b3-95f1-8f36b3bd6dcf">

2024-01-05 22:07 UTC, adidahiya commented on packages/core/src/components/entity-title/entityTitle.tsx
> +export const EntityTitle: React.FC<EntityTitleProps> = ({
can you add a `React.forwardRef()` here?

2024-01-05 22:07 UTC, adidahiya commented on packages/core/test/entity-title/entityTitleTests.tsx
> +    it("icon=null removes icon", () => {
I think a more common test case ought to be `icon={undefined}` or the prop is omitted, can we test that instead? I don't want to suggest that people need to set `icon={null}` explicitly to get the icon removed

2024-01-05 22:07 UTC, adidahiya commented on packages/demo-app/src/examples/EntityTitleExample.tsx
> +export class EntityTitleExample extends React.PureComponent {
nit: we're trying to only use function components rather than classes in newer code, could you refactor this to be an FC?

2024-01-08 15:01 UTC, adidahiya commented
opened a PR to address my CR comments: https://github.com/palantir/blueprint/pull/6633

2024-01-08 15:34 UTC, adidahiya approved these changes

2024-01-08 15:38 UTC, mud commented
thanks for addressing @adidahiya!

2024-01-08 15:48 UTC, adidahiya commented
<h3>[to/entity-title] address CR (#6633)</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/703e5fc2-a4fc-48fb-ab95-27d5f3300f06/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/703e5fc2-a4fc-48fb-ab95-27d5f3300f06/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/703e5fc2-a4fc-48fb-ab95-27d5f3300f06/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/703e5fc2-a4fc-48fb-ab95-27d5f3300f06/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

2024-01-08 16:02 UTC, merged