Feature: Add Prop to NonIdealState to Disable Muted Icon Style
palantir/blueprint pull request #6611
Opened 2023-12-18 17:11 UTC by AlexKempen

#### Introduction

This PR adds a prop `mutedIcon` to `NonIdealState` which can be used to explicitly opt-out of the muted style for the `icon`. This makes it possible to, for example, use an `<Icon>` component with an `intent` specified alongside `NonIdealState`, which is currently impossible since `Classes.NON_IDEAL_STATE_VISUAL` always overrides the `intent` (even when passing an explicit `<Icon>` JSX element). 

#### Checklist

- [x] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

This PR adds a `mutedIcon` prop to `NonIdealState`. `mutedIcon` defaults to `true` to preserve backwards-comparability. When set to `false`, `Classes.NON_IDEAL_STATE_VISUAL` is no longer applied to the `icon` prop, which can prevent issues with certain props getting overridden in an undesirable (and unexpected) way. 

#### Screenshot
Example of a `NonIdealState` with a custom `<Icon>` and `intent`:
![fix](https://github.com/palantir/blueprint/assets/89172296/078109e7-b62d-4038-b721-470976f84f23)

#### First Time Contributor Notes

As a first time contributor on this repo, I'll briefly discuss my experience getting the code to run and build. I first tried on my Windows 10 machine, which I ultimately gave up on. The primary issues I encountered there were:

- `windows-build-tools` refused to install for me. The primary suggestion I saw while troubleshooting was that it is now natively available with Node as an option during install. I'm not sure if that worked for me or not.
- Issues with `C:` paths being disallowed. The suggestion I saw while troubleshooting was to use a later version of Node (the post said they saw it resolved going from Node 12 to Node 16), but it was nevertheless occurring with the project's Node 18.

Since I couldn't find any fixes for the above issues, I eventually gave up and switched to Ubuntu in WSL, which worked much better. My main feedback there is that ChromeHeadless is needed to run `yarn test`, which isn't mentioned in the documentation (as far as I can tell). These commands resolved it for me:
```
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
```

2023-12-18 17:11 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @AlexKempen! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2023-12-20 16:54 UTC, adidahiya requested changes
Thanks for the PR and your notes about the contribution process @AlexKempen. I'm aware of development issues in Windows environments, we haven't had the bandwidth to fix them but we're open to PRs (see #6241)

As for the contents of this PR: I'd suggest moving the muted styling to an "icon modifier" class - see comments below. That would mean that `_non-ideal-state.scss` changes to:

```scss

.#{$ns}-non-ideal-state-visual {
  color: $gray3;
}
```

and the removed styles move to `_icon.scss`:

```scss
#{$ns}-icon {
  // ... existing styles

  &.#{$ns}-icon-muted svg {
    fill-opacity: 15%;
    // need to show overflow for some strokes on paths that reach the edge of the icon bounding box
    overflow: visible;

    path {
      stroke: $gray3;
      stroke-opacity: 50%;
      stroke-width: 0.5px;
    }
  }

  .#{$ns}-dark & {
    .#{$ns}-icon-muted svg {
      fill-opacity: 20%;
    }
  }
}
```

and we get a new string constant for the modifier class in `classes.ts`:

```ts
export const ICON_MUTED = `${ICON}-muted`;
```

2023-12-20 16:54 UTC, adidahiya commented on packages/core/src/components/non-ideal-state/nonIdealState.tsx
> +                    className={classNames(mutedIcon && Classes.NON_IDEAL_STATE_VISUAL)}
Let's not remove the class in this PR, as I think it is still semantically valuable to be able to target the "visual" element in the DOM here. Instead, let's adjust the styles to target a new class applied to the `<Icon>` element below.

2023-12-20 16:54 UTC, adidahiya commented on packages/core/src/components/non-ideal-state/nonIdealState.tsx
>                      <Icon icon={icon} size={iconSize} aria-hidden={true} tabIndex={-1} />
```suggestion
                    <Icon className={classNames({ [Classes.ICON_MUTED]: iconMuted })} icon={icon} size={iconSize} aria-hidden={true} tabIndex={-1} />
```

2023-12-20 16:54 UTC, adidahiya commented on packages/core/src/components/non-ideal-state/nonIdealState.tsx
> +    mutedIcon?: boolean;
nit: let's call this `iconMuted` to get the prop visually grouped with the other icon-related props in alphabetical sorting

```suggestion
    iconMuted?: boolean;
```

2023-12-20 16:54 UTC, adidahiya commented on packages/core/src/components/non-ideal-state/nonIdealState.tsx
> +                    className={classNames(mutedIcon && Classes.NON_IDEAL_STATE_VISUAL)}
```suggestion
                    className={Classes.NON_IDEAL_STATE_VISUAL}
```

2023-12-31 21:24 UTC, AlexKempen commented
@adidahiya ping since it's been a little while - is there anything else you'd like me to do with this?

2024-01-04 15:16 UTC, adidahiya approved these changes
looks great, thanks for making all those adjustments @AlexKempen!

the new prop looks good in [docs preview](https://output.circle-artifacts.com/output/job/2b8fbb9c-e753-4ce5-b428-0e0ccf1c86dd/artifacts/0/packages/docs-app/dist/index.html#core/components/non-ideal-state), and I was able to toggle it to `true` using React dev tools:

![image](https://github.com/palantir/blueprint/assets/723999/bc6a9e29-1bcf-490a-bff2-a8dff016fb27)

2024-01-04 15:18 UTC, merged