[icons]: team, trophy, soccer ball, sports stadium
palantir/blueprint pull request #6627
Opened 2024-01-04 22:26 UTC by jessperrin

#### Fixes #0000

#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

Soccer-based icons for an sports pilot.

![image](https://github.com/palantir/blueprint/assets/144474750/805f1e2a-2215-4124-8b20-d2d91ece0a93)

2024-01-04 22:34 UTC, adidahiya commented
<h3>Clean up PR a bit</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/3a93f30a-d0e9-4907-a797-a152fa912d42/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/3a93f30a-d0e9-4907-a797-a152fa912d42/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/3a93f30a-d0e9-4907-a797-a152fa912d42/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/3a93f30a-d0e9-4907-a797-a152fa912d42/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

2024-01-05 15:00 UTC, adidahiya requested changes
most of the icons look fine but 2 of them have extra markup that causes them to render incorrectly:

<img width="246" alt="image" src="https://github.com/palantir/blueprint/assets/723999/1aa8665b-c05c-4a2f-bc5a-fc6d3948eeca">

<img width="308" alt="image" src="https://github.com/palantir/blueprint/assets/723999/0026aa32-f5e3-42b3-852f-bcb819b5fed0">

2024-01-05 15:00 UTC, adidahiya commented on resources/icons/16px/sports-stadium.svg
> +<g clip-path="url(#clip0_1_17)">
I think the `<g>` wrapper and `<defs>` are superfluous, they should probably be removed from this file

2024-01-05 15:00 UTC, adidahiya commented on resources/icons/20px/sports-stadium.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
this version of the sports-stadium icon markup looks better :+1:

2024-01-05 15:00 UTC, adidahiya commented on resources/icons/20px/trophy.svg
> +<g clip-path="url(#clip0_1_13)">
same here, we should remove the `<g>` wrapper and the `<defs>` block

2024-01-05 17:21 UTC, jessperrin commented
Oh hm, would you mind making those changes? Not sure why those are there - is it due to something in the icon SVG?

2024-01-05 17:24 UTC, adidahiya commented
@jessperrin I'm not sure either, probably something to do with Figma export. Sure, I can make those fixes

2024-01-05 17:46 UTC, adidahiya commented
<h3>remove extraneous SVG markup</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/7c5aa3e4-eaf3-44ac-818c-95162bc6f1b9/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/7c5aa3e4-eaf3-44ac-818c-95162bc6f1b9/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/7c5aa3e4-eaf3-44ac-818c-95162bc6f1b9/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/7c5aa3e4-eaf3-44ac-818c-95162bc6f1b9/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

2024-01-05 18:01 UTC, adidahiya approved these changes

2024-01-05 18:02 UTC, merged