fix #6734 checkbox icon opacity issue
palantir/blueprint pull request #6758
Opened 2024-04-05 16:28 UTC by JamesHighsmith

#### Fixes #0000

This pull request addresses an issue with the opacity of the checkbox icon in its disabled state. Previously, the opacity was set to 0.6, which did not provide enough contrast against the background, making it hard to distinguish for some users.

Changes proposed in this pull request:
Adjust the opacity of the checkbox icon in the disabled state from 0.6 to 0.5, improving visibility and design consistency.
Reviewers should focus on:
The change in _controls.scss for the checkbox icon opacity. Ensure this adjustment does not affect other components or create visual regressions in different states.
Screenshot:
No visual change significant enough to require a screenshot, but the difference can be observed in disabled checkboxes across the application where this change applies.

This minor adjustment ensures better consistency with the design language and improves the user experience by making the disabled state more distinguishable.

2024-04-05 16:29 UTC, palantirtech commented
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @JamesHighsmith! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2024-08-13 02:03 UTC, ggdouglas commented
On inspection of this, I don't see the proposed changes going into effect. This is what I'm seeing, where the checked and indeterminate states are still at 100% opacity. 

![Screenshot 2024-08-12 at 21 26 39@2x](https://github.com/user-attachments/assets/ece54ad8-82e8-4efd-8721-466747b35eda)

Since the indicator icon is a embedded SVG icon, it doesn't inherit the `color` of the `.bp5-control-indicator` class.

Instead, could we set the opacity directly on the `::before` element? It would look something like:
```scss
&.#{$ns}-checkbox {
  // ...
  input:disabled ~ .#{$ns}-control-indicator::before {
    opacity: 0.5;
  }
  // ...
}
```
This would be similar to what we already do for reducing the opacity on disabled radio button indicators https://github.com/palantir/blueprint/blob/4767947f098c4604e2e38d212a8973d7d39f6df5/packages/core/src/components/forms/_controls.scss#L320-L321

![Screenshot 2024-08-12 at 22 01 56@2x](https://github.com/user-attachments/assets/43530b4c-baf5-4105-8b0a-1dc5cfaa2a85)

2024-08-22 14:38 UTC, ggdouglas requested changes
Supportive of the change here, but we need some slightly more targeted styles to get the desired effect.

2024-09-05 15:56 UTC, ggdouglas commented
Fixed in #6962

2024-09-05 15:56 UTC, closed without merging