Fix DateRangeInput3 closing on time change
palantir/blueprint pull request #6782
Opened 2024-05-02 16:30 UTC by moon1ock

`this.props.timePrecision` which is supposed to be an alias for `this.props.timePickerProps.precision` seems to be never set and is always null.

2024-05-02 16:45 UTC, svc-palantir-github commented
<h3>Add generated changelog entries</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/60bcf544-7726-4e8a-b63b-8699e51f5394/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/60bcf544-7726-4e8a-b63b-8699e51f5394/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/60bcf544-7726-4e8a-b63b-8699e51f5394/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/60bcf544-7726-4e8a-b63b-8699e51f5394/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

2024-05-02 19:14 UTC, svc-palantir-github commented
<h3>but i ran prettier... and yarn lint-fix... and yarn format</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/8358893c-9c7e-46aa-aec0-a34a9bae3c08/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/8358893c-9c7e-46aa-aec0-a34a9bae3c08/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/8358893c-9c7e-46aa-aec0-a34a9bae3c08/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/8358893c-9c7e-46aa-aec0-a34a9bae3c08/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

2024-05-03 19:30 UTC, ericjeney requested changes
Thanks for spotting this and digging in to where the bug is, @moon1ock!

I don't think we should merge this docs change, though. I'd like the docs to continue to represent the "good" / expected ways that people should use components, rather than make it seem like this bug is an expected part of our API.

I recognize that's not a very satisfying answer since we haven't fixed the bug itself yet, but I'm glad you found a workaround that should work for you in your codebase at least. 🙂

2024-06-28 14:17 UTC, evansjohnson commented
closing in favor of https://github.com/palantir/blueprint/pull/6881 to fix the underlying issue - thank you for the lead on this!

2024-06-28 14:17 UTC, closed without merging